### PR TITLE
Add self update

### LINKED ISSUE #37: Add a self-update command
Currently we have no way to update `captain` using captain itself so if we want to have the last version we have to check Github and install the last version manually.

I'd like to propose a new command `captain self-update` that download the last version (if any) and update the binary in the computer.

In order to have `captain self-update` we should:

- store the binaries in `$HOMEDIR/.captain/binaries/captain-{captain version}`
- have a symlink `$HOMEDIR/.captain/bin/captain` that points to the last binary (this dir should be in the users's `$PATH`)
- store in github the last version of `captain`. E.g. `https://raw.githubusercontent.com/harbur/captain/master/VERSION`

##### How should it work?

1. User run `captain self-update`
1. `captain` check the last version in `https://raw.githubusercontent.com/harbur/captain/master/VERSION`
1. (if new version available) download the last version and store it in `$HOMEDIR/.captain/binaries/captain-{version}`
1. Update `captain` symlink in `$HOMEDIR/.captain/bin/`

What do you think? Have I missed something?

### PR DESCRIPTION
**Pull request by dgil**
This PR adds `captain self-update`.

Resolves #37

### CODE REVIEW

**Comment by dgil** [comment]
ping @spiddy

**Comment by spiddy** [comment]
Missing on README documentation how to add the ~/.captain/bin/ directory to the PATH.

**Comment by dgil** [comment]
I've updated the `readme` to include `self-update` command. 

About including `~/.captain/bin/` to the `$PATH`: I think this should be handled in #52 as is part of the installation process.

**Comment by spiddy** [comment]
LGTM

**Pull request merged**
