### PR TITLE
upgrade to the latest version of fsouza/go-dockerclient to avoid post…

### PR DESCRIPTION
**Pull request by jurgenweber**
…/socket issues

I found when attempting to build master that I ran into: https://github.com/harbur/captain/issues/66#issuecomment-313536056

This is because the version of go-dockerclient pinned is old and using deprecated functions in other dependencies.

update to latest, it builds and works now.

### CODE REVIEW

**Comment by jurgenweber** [comment]
also gave it a version bump so it can be released with the exit code fix.

**Comment by jurgenweber** [comment]
@spiddy ping.

Thanks

**Comment by joeruello** [comment]
Would be great this merged :)

**Comment by estahn** [comment]
@spiddy #74

**Comment by spiddy** [comment]
Done thanks 👍

**Comment by spiddy** [comment]
New release is out v1.1.1

**Pull request merged**
